version: '3'
services:
    api-service:
        build:
            context: ./backend
            dockerfile: ./docker-backend.dockerfile
        volumes:
            - ./backend:/app
        ports:
            -   "3003:3000"
        restart: always
        deploy:
            mode: replicated
            replicas: 1  
        depends_on:
            -   mongo
            -   redis
        networks:
            - mgtest

    mongo:
        image: 'mongo:latest'
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_DATABASE: profiles
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - ./db-data/mongo/:/data/db
        networks:
            - mgtest

    redis:
        image: redis:latest
        restart: always
        networks:
            - mgtest
networks:
    mgtest:
        